# -*- coding: utf-8 -*-
"""KMeans.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E_K4Jg3yis4-92GGqHxnB8IcpiVzvnEb
"""

# Commented out IPython magic to ensure Python compatibility.
#Importing the library 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
from sklearn.metrics import accuracy_score

df=pd.read_csv('/content/KMeans_Iris_dataset.csv')

df.head()

df.shape

#df.describe()
#df.isnull.sum

#Data Preprocessing
X=df.drop(['Species'],axis=1)

y=df['Species']

X

y

#data training
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

#X_train
#y_train
#X_test 
#y_test

## K-MEANS Clustering

X=df.drop(['Species'],axis=1)
X

from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

y=le.fit_transform(y)

y

from sklearn.cluster import KMeans
km=KMeans(n_clusters=3,random_state=2,n_jobs=4)
km.fit(X)

#For prediction
Catagory_kmeans=['Iris-Versicolor', 'Iris-Setosa', 'Iris-Virginica']
X_km=np.array([[1 ,1, 1, 1,1]])

X_km_prediction=km.predict(X_km)
print(Catagory_kmeans[int(X_km_prediction[0])])

#Lets see in Graph
colormap=np.array(['Red','green','blue'])
fig=plt.scatter(df['PetalLengthCm'],df['PetalWidthCm'],c=colormap[y],s=50)

